// ─── /app/lib/welcomeScripts.js ──────────────────────────────────────────────
// Static welcome scripts for the avatar opening statement.
// These are NOT generated by Claude — they are fixed, crafted scripts
// that play on first visit. No API call needed, instant playback.
//
// Why static:
//   - Faster (no Claude latency on first impression)
//   - Consistent (every new user gets the same crafted message)
//   - Cost-free (no API credits for the most-played video)
//   - Controlled (you approve every word)
//
// Mario should record these himself for voice cloning reference material.
// Each script is ~90 seconds when spoken at natural pace.
//

export const WELCOME_SCRIPTS = {

  // ── PRIMARY WELCOME — plays on first app open ──────────────────────────
  // This is the one. The first thing a new user sees.
  //
  welcome: `Your body is the most sophisticated system ever built. Four hundred trillion cells. Five hundred million years of evolution. A molecular intelligence that knows exactly what it needs — and has been trying to tell you.

But somewhere along the way, we stopped listening. We replaced real food with processed calories. We silenced the signals with medication. And we accepted fatigue, brain fog, and inflammation as normal. They are not normal. They are your biology asking for help.

Meet Mario exists because I believe medicine should translate, not guess. Every person who walks through our doors — or opens this app — deserves to know what their cells are actually saying. Not what a blood test approximates. What the cell itself contains, what the immune system is reacting to, and what the DNA has been shaping since before you were born.

This platform connects those layers for the first time. Your immune reactivity. Your cellular nutrition. Your genetic architecture. And from that data, a protocol — precise, personalised, built for your biology alone.

We have done this for twenty-five thousand patients. And we have seen what happens when the immune system is finally heard. Energy returns. Clarity returns. The body remembers what it was designed to do.

This is not a diet app. This is not a wellness trend. This is precision medicine — made accessible to everyone, everywhere.

Welcome to Meet Mario. Let us begin.`,


  // ── RETURNING USER — plays after first results are uploaded ─────────────
  results_ready: `Your results are in.

I have reviewed your data, and I want to walk you through what I see. But first, I want you to understand something important.

These results are not a verdict. They are a snapshot — a picture of where your immune system is right now, in this moment. And immune systems change. That is the entire point of what we are about to do together.

What I am going to show you is which foods are currently driving inflammation in your body, which nutrients your cells are actually absorbing — not what your blood says, but what your cells have — and if you have uploaded genomic data, which genetic variants shape how your body processes everything from folate to toxins.

From this data, I have built your protocol. Twenty-one days. Six meals a day. Every meal designed around your specific biology.

The first week will be the hardest. You may feel worse before you feel better — that is normal. Your immune system is recalibrating. By day ten, most of my patients report the fog lifting. By day twenty-one, you will understand what your body has been trying to tell you.

Tap on any section to explore your results. Or ask me anything — I am right here.`,


  // ── INVESTOR / DEMO — for presentations and pitches ────────────────────
  demo: `This is Meet Mario — the world's first clinical AI platform built on real patient data.

Behind this interface is fifteen years of clinical practice, twenty-five thousand patients, and a proprietary framework for understanding why modern humans get sick.

The core insight is this: the human innate immune system is a five-hundred-million-year-old pattern recognition library. It knows what food is. And most of what we eat today, it does not recognise.

The result is silent inflammation. Not allergies. Not intolerances in the traditional sense. A low-grade, chronic immune activation that drives fatigue, brain fog, gut dysfunction, weight resistance, and a cascade of symptoms that conventional medicine cannot explain.

This platform does three things no other technology does.

One — it integrates immune reactivity data, cellular micronutrient status, and genomic variants into a single patient model. No other app connects these layers.

Two — it translates that data into a precise, day-by-day protocol. Not recommendations. A protocol — built on the specific foods this patient's immune system can tolerate.

Three — it learns. Every patient who uses this platform improves the population-level model for the next patient. Twenty-five thousand patients in. The dataset is already the largest of its kind in functional medicine.

The platform serves patients internationally. It is designed to scale across multiple markets. And the lab partners are interchangeable — the intelligence layer belongs to us.

This is not a wellness app. This is a clinical operating system for longevity medicine.`,

}


// ── Helper to get the right script based on user state ────────────────────
export function getWelcomeScript(patient) {
  if (!patient || !patient.name) {
    return { id: 'welcome', script: WELCOME_SCRIPTS.welcome }
  }
  if (patient.severe?.length > 0 || patient.moderate?.length > 0) {
    return { id: 'results_ready', script: WELCOME_SCRIPTS.results_ready }
  }
  return { id: 'welcome', script: WELCOME_SCRIPTS.welcome }
}
