// ─── /app/lib/welcomeScripts.js ──────────────────────────────────────────────
// Static welcome scripts for the avatar opening statement.
// These are NOT generated by Claude — they are fixed, crafted scripts
// that play on first visit. No API call needed, instant playback.
//
// Why static:
//   - Faster (no Claude latency on first impression)
//   - Consistent (every new user gets the same crafted message)
//   - Cost-free (no API credits for the most-played video)
//   - Controlled (you approve every word)
//
// Mario should record these himself for voice cloning reference material.
// Each script is ~90 seconds when spoken at natural pace.
//

export const WELCOME_SCRIPTS = {

  // ── PRIMARY WELCOME — plays on first app open ──────────────────────────
  // This is the one. The first thing a new user sees.
  //
  welcome: `Welcome to Meet Mario.

My name is Mario Anthis. I am a physician, and I have spent the last fifteen years trying to answer one question. Why do intelligent, health-conscious people still feel terrible?

The answer, in most cases, is not what you expect. It is not a missing diagnosis. It is not stress. It is not in your head. It is in your immune system — reacting silently to foods you eat every single day.

Your body has been trying to tell you this for years. The bloating after meals. The brain fog that comes and goes. The fatigue that sleep does not fix. These are not random symptoms. They are signals. And they follow a pattern that, once you see it, changes everything.

This platform was built to translate those signals into a language you can act on. Here is what it does.

First, it builds a profile of your biology. Your immune reactivity, your cellular nutrition, your genetic architecture. Not one test — a complete picture.

Second, it gives you a protocol. Not a generic diet. A precise, personalised elimination sequence based on your own data — designed to lower your immune burden in twenty-one days.

Third, it tracks your progress. Every meal, every symptom, every change — mapped over time so you can see your body responding.

And fourth — me. I am here, inside this app, whenever you need to understand what your results mean, what to eat tomorrow, or why you feel worse before you feel better.

This is precision medicine. Not guesswork. Not trends. Your biology, translated.

Let us begin.`,


  // ── RETURNING USER — plays after first results are uploaded ─────────────
  results_ready: `Your results are in.

I have reviewed your data, and I want to walk you through what I see. But first, I want you to understand something important.

These results are not a verdict. They are a snapshot — a picture of where your immune system is right now, in this moment. And immune systems change. That is the entire point of what we are about to do together.

What I am going to show you is which foods are currently driving inflammation in your body, which nutrients your cells are actually absorbing — not what your blood says, but what your cells have — and if you have uploaded genomic data, which genetic variants shape how your body processes everything from folate to toxins.

From this data, I have built your protocol. Twenty-one days. Six meals a day. Every meal designed around your specific biology.

The first week will be the hardest. You may feel worse before you feel better — that is normal. Your immune system is recalibrating. By day ten, most of my patients report the fog lifting. By day twenty-one, you will understand what your body has been trying to tell you.

Tap on any section to explore your results. Or ask me anything — I am right here.`,


  // ── INVESTOR / DEMO — for presentations and pitches ────────────────────
  demo: `This is Meet Mario — the world's first clinical AI platform built on real patient data.

Behind this interface is fifteen years of clinical practice, twenty-five thousand patients, and a proprietary framework for understanding why modern humans get sick.

The core insight is this: the human innate immune system is a five-hundred-million-year-old pattern recognition library. It knows what food is. And most of what we eat today, it does not recognise.

The result is silent inflammation. Not allergies. Not intolerances in the traditional sense. A low-grade, chronic immune activation that drives fatigue, brain fog, gut dysfunction, weight resistance, and a cascade of symptoms that conventional medicine cannot explain.

This platform does three things no other technology does.

One — it integrates immune reactivity data, cellular micronutrient status, and genomic variants into a single patient model. No other app connects these layers.

Two — it translates that data into a precise, day-by-day protocol. Not recommendations. A protocol — built on the specific foods this patient's immune system can tolerate.

Three — it learns. Every patient who uses this platform improves the population-level model for the next patient. Twenty-five thousand patients in. The dataset is already the largest of its kind in functional medicine.

The platform serves patients internationally. It is designed to scale across multiple markets. And the lab partners are interchangeable — the intelligence layer belongs to us.

This is not a wellness app. This is a clinical operating system for longevity medicine.`,

}


// ── Helper to get the right script based on user state ────────────────────
export function getWelcomeScript(patient) {
  if (!patient || !patient.name) {
    return { id: 'welcome', script: WELCOME_SCRIPTS.welcome }
  }
  if (patient.severe?.length > 0 || patient.moderate?.length > 0) {
    return { id: 'results_ready', script: WELCOME_SCRIPTS.results_ready }
  }
  return { id: 'welcome', script: WELCOME_SCRIPTS.welcome }
}
